import type { Metadata } from "next";
import {Sora } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";


const sora = Sora({ subsets: ['latin'], weight: ['400', '700'] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${sora.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
